# Generated by Django 5.0.6 on 2024-05-13 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marcas',
            name='marca',
            field=models.CharField(max_length=55),
        ),
        migrations.AlterField(
            model_name='modelos',
            name='modelo',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='tipo',
            name='tipo',
            field=models.CharField(max_length=55, unique=True),
        ),
    ]
