# Generated by Django 5.0.6 on 2024-05-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ver_vehiculos',
            name='marcas',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ver_vehiculos',
            name='modelos',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='ver_vehiculos',
            name='tipo',
            field=models.CharField(max_length=30),
        ),
    ]
