# Generated by Django 5.0.6 on 2024-05-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0004_descripcion_ver_vehiculos_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcion',
            name='descripcion',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
