# Generated by Django 5.0.6 on 2024-05-30 21:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0005_alter_descripcion_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ver_vehiculos',
            name='fecha_actulizacion',
            field=models.DateField(blank=True, default=django.utils.timezone.now, editable=False, null=True),
        ),
    ]
