# Generated by Django 5.0.6 on 2024-05-30 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0007_rename_fecha_actulizacion_ver_vehiculos_fecha_actualizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ver_vehiculos',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='ver_vehiculos',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
