# Generated by Django 5.0.4 on 2024-06-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_ver_vehiculos_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ver_vehiculos',
            name='contacto_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ver_vehiculos',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ver_vehiculos',
            name='contacto_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ver_vehiculos',
            name='descripcion',
            field=models.TextField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='ver_vehiculos',
            name='marcas',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ver_vehiculos',
            name='modelos',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ver_vehiculos',
            name='tipo',
            field=models.CharField(max_length=50),
        ),
    ]
