# Generated by Django 5.0.4 on 2024-06-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0009_ver_vehiculos_contacto_email_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Descripcion',
        ),
        migrations.DeleteModel(
            name='Precio',
        ),
    ]
